@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!includeurl https://raw.githubusercontent.com/skleanthous/C4-PlantumlSkin/master/build/output/c4.puml

'skinparam linetype polyline
'skinparam linetype ortho

' uncomment the following line and comment the first to use locally
' !include C4_Deployment.puml

'AddTagSupport("fallback", $bgColor="#c0c0c0")
WithoutPropertyHeader()

' dynamic legend is used (activated in last line)
' LAYOUT_WITH_LEGEND()

title Deployment Diagram for chat system

Deployment_Node(chatLoadBalancerNode,"Chat load balancer","","Spring Cloud Load Balancer"){
    Container(chatLoadBalancer, "Chat load balancer", "java", "Balances traffic between different instances of the chat application", $sprite="java")
}

Deployment_Node_R(gatewayNode," "," "){
  Container(gateway, "API Gateway", "java", "Handles all business logic", $sprite="java")
}

Deployment_Node_R(chatAppNode," "," "){
  Container(chatapp, "ChatApp", "Spring Reactive Streams", "It implements the logic of the chat. Receives a message from the sender and checks if the recipient has an open connection locally. If so, it sends a message, if not, it identifies the correct instance (using the register) that serves the given recipient. The message goes to the correct queue.", $sprite="java")
}

Deployment_Node_R(chatinstanceDiscoveryNode," "," "){
  Container(chatinstanceDiscovery, "ChatInstanceDiscovery", "java", "Component containing a registry of instances and open connections. It is able to find the instance based on the ID of the message recipient (connection owner). ", $sprite="java")
}

Deployment_Node_R(chatqueueNode," "," "){
  ContainerQueue(chatqueue, "Chat Queue", "java", "Component  forwarding messages to the instance containing the connection to the recipient of the chat message.The actual queue is identified on the basis of the chat message addressee ID. ", $sprite="java")
}

Deployment_Node_R(chatDbNode," "," "){
  ContainerDb(db, "Database", "Mongo DB", "Holds chat message history for user", $sprite="msql_server")
}

@enduml